config/routes.rb
TimeRecording::Application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }

  root :to => 'home#index'

  resources :user
  
  resources :time_records do
    collection do
      post 'create_time_record'
      get 'edit_multiple'
      post 'update_multiple'
      post 'create_multiple'
      get 'edit_previous_month_timings'
      post 'update_previous_month_timings'
    end
  end

  resources :admins do
    member do
      get 'approve_user'
      get 'reject_user'
      delete 'destroy_user'
    end
  end

  match 'time_records' => 'time_records#index', as: :user_root
  match 'dashboard' => 'home#dashboard'#, as: :admin_index

  match 'about_us' => 'home#about_us'
  match 'instructions' => 'home#instructions'
  match 'contact' => 'home#contact'

  

end

app/views/admins/index.html.erb
<div id="content_wrapper">
  <div id="content">
    <img class="scrollButtons left" src="" alt=""/>
    <div class="scroll" style="overflow: hidden;">
      <div class="scrollContainer" style="width: 4300px;">
        <div class="panel" id="home" style="float: left; position: relative;">
          <div class="col_800 float_l">
            <h1 style="text-align: center"> Welcome Admin </h1>
            <br/>
            <h1> List of users </h1>
            <table class="simple_table" >
              <tr>
                <th>User email address</th>
                <th>Status</th>
                <th>Delete</th>
              </tr>
              <% @total_users.each do |user| %>
                <tr>
                  <td><%= user.email %></td>

                  <% if user.approved_by_admin %>
                    <td><%= link_to "‎Reject", reject_user_admin_path(id: user.id), style: "color: #000" %></td>
                  <% else %>
                    <td><%= link_to "‎Approve", approve_user_admin_path(id: user.id), style: "color: #000" %></td>
                  <% end %>
                  <td>
                    <%= link_to 'Remove User', destroy_user_admin_path(id: user.id), style: "color: #000", confirm: 'Are You Sure Want To Remove The User ?', method: :delete %>
                  </td>
                </tr>
              <% end %>
            </table>
          </div>
          <div class="cleaner_h20"></div>
        </div>
      </div>
    </div>
  </div>
</div>