config/routes.rb
TimeRecording::Application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }

  root :to => 'home#index'

  resources :user
  
  resources :time_records do
    collection do
      post 'create_time_record'
      get 'edit_multiple'
      post 'update_multiple'
      post 'create_multiple'
      get 'edit_previous_month_timings'
      post 'update_previous_month_timings'
    end
  end

  resources :admins do
    member do
      get 'approve_user'
      get 'reject_user'
      delete 'destroy_user'
    end
  end

  match 'time_records' => 'time_records#index', as: :user_root
  match 'dashboard' => 'home#dashboard'#, as: :admin_index

  match 'about_us' => 'home#about_us'
  match 'instructions' => 'home#instructions'
  match 'contact' => 'home#contact'

  

end

app/models/time_record.rb
class TimeRecord < ActiveRecord::Base
  attr_accessible :date, :in_time, :out_time, :user_id, :attended_hours, :total_hours, :current_month_timing,
    :previous_month_data, :later_month_data, :updated_previous_month_data, :updated_later_month_data

  belongs_to :user

  #  validates :date, presence: {message: "required field cannot be blank"}
  #  validates :in_time, presence: {message: "required field cannot be blank"}
  #  validates :out_time, presence: {message: "required field cannot be blank"}


  def self.update_privious_month_timing(user, current_month_timings)
    #self.update_attributes(updated_previous_month_data: true)
    record = self.where("user_id = ? ", user.id).first
    record.update_attributes(previous_month_data: current_month_timings, updated_previous_month_data: true )
  end

  def self.update_current_month_timing(user, current_month_timings)
    msg = false
    record = self.where("user_id = ? ", user.id).first
    if record.update_attributes(current_month_timing: current_month_timings)
      msg = true
    else
      msg = false
    end

    return msg
  end

  def self.create_new_time_record(user_id, current_month_timings)
    msg = false
    if self.create(user_id: user_id, current_month_timing: current_month_timings)
      msg = true
    else
      msg = false
    end

    return msg
  end
  
end

app/controllers/time_records_controller.rb
class TimeRecordsController < ApplicationController

  require 'time_diff'
  
  before_filter :authenticate_user!
  before_filter :authenticate_user_aprooval
    
  def index
    if !current_user.blank? && current_user.admin
      redirect_to admins_path
    else
    
      unless current_user.time_record.current_month_timing.blank?
        @current_time_records = ActiveSupport::JSON.decode(current_user.time_record.current_month_timing).to_hash
        @previous_time_records = ActiveSupport::JSON.decode(current_user.time_record.previous_month_data).to_hash
      end
      
    end
  end

  def new
    record = TimeRecord.where("user_id = ? ", current_user.id).first
    
    if record.current_month_timing.blank?
      render action: "new"
    else
      redirect_to edit_multiple_time_records_path
    end
  end

  def edit_multiple
    if current_user.time_record.blank?
      render action: "new"
    else
      @time_records = ActiveSupport::JSON.decode(current_user.time_record.current_month_timing).to_hash
    end
  end

  def update_multiple

    total_hours = "09:00"

    user_fday = current_user.first_day_of_month

    month = 1
    i = 1

    if user_fday <= Date.today.day
      month =  Date.today.month
    else
      month =  Date.today.month - 1
    end
    sdate =  Date.new(2013, month, user_fday)
    
    (sdate..Date.today).each do |date|
      unless DateTime.parse("#{date}").strftime("%A") == "Saturday" || DateTime.parse("#{date}").strftime("%A") == "Sunday"
        if  params[:time_record][:current_month_timing]["#{i}"][:in_time].blank? || params[:time_record][:current_month_timing][i.to_s][:out_time].blank?
          params[:time_record][:current_month_timing]["#{i}"].merge!(:attended_hours => "", :total_hours => total_hours)
        else
          attended_hours = Time.diff(Time.parse(params[:time_record][:current_month_timing]["#{i}"][:out_time]), Time.parse(params[:time_record][:current_month_timing]["#{i}"][:in_time]), "%h:%m")
          params[:time_record][:current_month_timing]["#{i}"].merge!(:attended_hours => attended_hours[:diff], :total_hours => total_hours)
        end
        i += 1
      end
    end
    i = 1
    params[:time_record].merge!(:user_id => current_user.id)

    params[:time_record][:current_month_timing] = params[:time_record][:current_month_timing].to_json


    record = TimeRecord.where("user_id = ? ", current_user.id).first
    if record.blank?
      if TimeRecord.create(user_id: params[:time_record][:user_id], current_month_timing: params[:time_record][:current_month_timing])
        flash[:notice] = "create success"
        redirect_to time_records_path
      else
        flash[:notice] = "create error"
        redirect_to edit_multiple_time_records_path
      end
    else
      if record.update_attributes(current_month_timing: params[:time_record][:current_month_timing])
        unless record.updated_previous_month_data
          time_record = record.current_month_timing
          user_fday = current_user.first_day_of_month
          if (Date.today.day == user_fday - 1)
            TimeRecord.update_privious_month_timing(current_user, time_record)
          end
        end
        if Date.today.day == user_fday + 1
          record.update_attributes(updated_previous_month_data: false)
        end
          
        flash[:notice] = "Update success"
        redirect_to time_records_path
      else
        flash[:notice] = "Update error"
        redirect_to edit_multiple_time_records_path
      end
    end

  end

  def create_multiple

    total_hours = "09:00"
    user_fday = current_user.first_day_of_month
    month = 1
    i = 1

    if user_fday <= Date.today.day
      month =  Date.today.month
    else
      month =  Date.today.month - 1
    end
    sdate =  Date.new(2013, month, user_fday)

    (sdate..Date.today).each do |date|
      unless DateTime.parse("#{date}").strftime("%A") == "Saturday" || DateTime.parse("#{date}").strftime("%A") == "Sunday"
        if  params[:time_record][:current_month_timing]["#{i}"][:in_time].blank? || params[:time_record][:current_month_timing][i.to_s][:out_time].blank?
          params[:time_record][:current_month_timing]["#{i}"].merge!(:attended_hours => "", :total_hours => total_hours)
        else
          attended_hours = Time.diff(Time.parse(params[:time_record][:current_month_timing]["#{i}"][:out_time]), Time.parse(params[:time_record][:current_month_timing]["#{i}"][:in_time]), "%h:%m")
          params[:time_record][:current_month_timing]["#{i}"].merge!(:attended_hours => attended_hours[:diff], :total_hours => total_hours)
        end
        i += 1
      end
    end
    i = 1
    params[:time_record].merge!(:user_id => current_user.id)
    
    params[:time_record][:current_month_timing] = params[:time_record][:current_month_timing].to_json

    record = TimeRecord.where("user_id = ? ", current_user.id).first
    if record.blank?
      msg = TimeRecord.create_new_time_record(params[:time_record][:user_id], params[:time_record][:current_month_timing])
    else
      msg = TimeRecord.update_current_month_timing(current_user, params[:time_record][:current_month_timing])
    end
    
    if msg
      flash[:notice] = "Update success"
      redirect_to time_records_path
    else
      flash[:notice] = "Update error"
      redirect_to edit_multiple_time_records_path
    end

  end

  def edit_previous_month_timings
    unless current_user.time_record.previous_month_data.blank?
      @previous_time_records = ActiveSupport::JSON.decode(current_user.time_record.previous_month_data).to_hash
    end
  end

  def update_previous_month_timings
    
    total_hours = "09:00"
    first_index = params[:time_record][:previous_month_timing].keys.first.to_s
    
    fd = params[:time_record][:previous_month_timing][first_index]["date"].to_date
    ld = params[:time_record][:previous_month_timing][first_index]["date"].to_date + 30
    i = 1
    
    (fd..ld).each do |date|
      unless DateTime.parse("#{date}").strftime("%A") == "Saturday" || DateTime.parse("#{date}").strftime("%A") == "Sunday"
        if  params[:time_record][:previous_month_timing]["#{i}"][:in_time].blank? || params[:time_record][:previous_month_timing][i.to_s][:out_time].blank?
          params[:time_record][:previous_month_timing]["#{i}"].merge!(:attended_hours => "", :total_hours => total_hours)
        else
          attended_hours = Time.diff(Time.parse(params[:time_record][:previous_month_timing]["#{i}"][:out_time]), Time.parse(params[:time_record][:previous_month_timing]["#{i}"][:in_time]), "%h:%m")
          params[:time_record][:previous_month_timing]["#{i}"].merge!(:attended_hours => attended_hours[:diff], :total_hours => total_hours)
        end
        i += 1
      end
    end
    params[:time_record].merge!(:user_id => current_user.id)

    params[:time_record][:previous_month_timing] = params[:time_record][:previous_month_timing].to_json

    #raise params[:time_record][:previous_month_timing].inspect
    record = TimeRecord.where("user_id = ? ", current_user.id).first
    if record.update_attributes(previous_month_data: params[:time_record][:previous_month_timing])
      flash[:notice] = "Update success"
      redirect_to time_records_path(previous: true)
    else
      flash[:notice] = "Update error"
      redirect_to edit_multiple_time_records_path
    end
    
  end

end

app/helpers/time_records_helper.rb
module TimeRecordsHelper
end

app/views/time_records/_current_month.html.erb
<% require 'date' %>
<% require 'time_diff' %>

<% first_index = @current_time_records.keys.first.to_s %>
<% last_index = @current_time_records.keys.last.to_s %>
<% #raise last_index.to_i.inspect %>
<% i = first_index.to_i %>
<ul id="navbar">
  <%= link_to("click here to view previous month timings", time_records_path(previous: true)) %>
</ul>
<table style="width: 100%; text-align: center;" class="simple_table1">
  <tr>
    <th>Date</th>
    <th>In Time</th>
    <th>Out Time</th>
    <th>Attended Hours</th>
    <th>Total Hours</th>
  </tr>
  <% #raise @time_records.inspect %>
  <% unless  @current_time_records.blank? %>
    <% while i <= last_index.to_i %>
      <% if @current_time_records["#{i}"]["in_time"].blank? || @current_time_records["#{i}"]["out_time"].blank? %>
        <% i += 1 %>
        <%  if i > last_index.to_i %>
          <% break %>
        <% end %>
      <% else %>
        <tr>
          <td><%= @current_time_records["#{i}"]['date'] %></td>
          <td><%= @current_time_records["#{i}"]["in_time"] %></td>
          <td><%= @current_time_records["#{i}"]["out_time"] %></td>
          <td><%= @current_time_records["#{i}"]["attended_hours"] %></td>
          <td><%= @current_time_records["#{i}"]["total_hours"] %></td>
        </tr>
        <% i += 1 %>
      <% end %>

    <% end %>
    <% i = 1 %>
  <% end %>
</table>

<div class="cleaner_h10"></div>

<% unless  @current_time_records.blank? %>
  <% attended_seconds = 0 %>
  <% total_seconds = 0 %>
  <% #raise @current_time_records.keys.last.inspect %>
  <% while i <= last_index.to_i %>

    <% if @current_time_records["#{i}"]["attended_hours"].blank? %>
      <% i += 1 %>
      <%  if i > last_index.to_i %>
        <% break %>
      <% end %>
    <%  else %>
      <% attended_date_time = DateTime.parse(@current_time_records["#{i}"]["attended_hours"]) %>
      <% total_date_time = DateTime.parse(@current_time_records["#{i}"]["total_hours"]) %>
      <% p "...................#{attended_date_time}" %>
      <% a_seconds = attended_date_time.hour * 3600 + attended_date_time.min * 60 %>
      <% t_seconds = total_date_time.hour * 3600 + total_date_time.min * 60 %>

      <%  attended_seconds += a_seconds %>
      <%  total_seconds += t_seconds %>
      <% i += 1 %>
    <% end %>

  <% end %>

  <% i = first_index.to_i %>

  <% attended_hours = attended_seconds / 3600.to_i %>
  <% attended_minutes = (attended_seconds / 60 - attended_hours * 60).to_s %>

  <% if attended_minutes.to_i < 10 %>
    <% total_attended_time = "#{attended_hours} : 0#{attended_minutes.to_s}" %>
  <% else %>
    <% total_attended_time = "#{attended_hours} : #{attended_minutes}" %>
  <% end %>



  <% total_hours = total_seconds / 3600.to_i %>
  <% total_minutes = (total_seconds / 60 - total_hours * 60).to_i %>
  <% total_time = "#{total_hours} : #{total_minutes}" %>

  <% if total_hours < 10 && total_minutes < 10 %>
    <% total_time = "0#{total_hours} : 0#{total_minutes}" %>
  <% elsif total_minutes < 10 %>
    <% total_time = "#{total_hours} : 0#{total_minutes}" %>
  <% elsif total_hours < 10 %>
    <% total_time = "0#{total_hours} : #{total_minutes}" %>
  <% else %>
    <% total_time = "#{total_hours} : #{total_minutes}" %>
  <% end %>

  <% if total_seconds < attended_seconds %>
    <% default_by_seconds = attended_seconds - total_seconds %>
    <% default_by_hours = default_by_seconds / 3600.to_i %>
    <% default_by_minutes = (default_by_seconds / 60 - default_by_hours * 60).to_i %>

    <% if default_by_minutes < 10 && default_by_hours < 10 %>
      <% default_by_total_time = "+ 0#{default_by_hours} : 0#{default_by_minutes}" %>
    <% elsif default_by_hours < 10 %>
      <% default_by_total_time = "+ 0#{default_by_hours} : #{default_by_minutes}" %>
    <% elsif default_by_minutes < 10 %>
      <% default_by_total_time = "+ #{default_by_hours} : 0#{default_by_minutes}" %>
    <% else %>
      <% default_by_total_time = "+ #{default_by_hours} : #{default_by_minutes}" %>
    <% end %>

  <% else %>
    <% default_by_seconds = total_seconds - attended_seconds %>
    <% default_by_hours = default_by_seconds / 3600.to_i %>
    <% default_by_minutes = (default_by_seconds / 60 - default_by_hours * 60).to_i %>
    <% if default_by_seconds == 0 %>
      <% default_by_total_time = "0#{default_by_hours} : 0#{default_by_minutes}" %>
    <% else %>
      <% default_by_total_time = "- #{default_by_hours} : #{default_by_minutes}" %>
    <% end %>

  <% end %>

  <% #default_by_total_time = Time.diff(Time.parse(total_time), Time.parse(total_attended_time), "%h:%m") %>

  <div class="cleaner"></div>
  <%=   %>
  <div class="cleaner"></div>
  <div class="attended_hours">
    <span>Attended hours</span><br/>
    <span><%= total_attended_time %></span>
  </div>

  <div class="attended_hours">
    <span>Total hours</span><br/>
    <span><%= total_time %></span>
  </div>

  <div class="attended_hours">
    <span>Default by</span><br/>
    <span><%= default_by_total_time %></span>
  </div>

<% end %>

app/views/time_records/_form.html.erb
<% require 'date' %>
<% require 'time_diff' %>

<div id="content_wrapper1">
  <div id="content1">
    <img class="scrollButtons left" src="" alt=""/>
    <div class="scroll" style="overflow: hidden;">
      <div class="scrollContainer" style="width: 4300px;">
        <div class="panel" id="home" style="float: left; position: relative;">
          <div id="contact_form">
            <% first_day = Time.now.strftime("%d").to_i %>
            <% user_fday = current_user.first_day_of_month %>

            <%
            month = 1
            i = 1
            time_record = {}
          %>
            <% if user_fday <= Date.today.day
              month =  Date.today.month
            else
              month =  Date.today.month - 1
            end %>

            <% sdate =  Date.new(2013, month, user_fday) %>
            <% edate =  sdate + 30 %>

            <%= form_tag create_multiple_time_records_path, method: 'post' do |f| %>


              <table style="width: 100%; text-align: center" >
                <tr>
                  <th style="font-size: 20px;">Date</th>
                  <th style="font-size: 20px;">In Time</th>
                  <th style="font-size: 20px;">Out Time</th>
                </tr>

                <%  #raise @time_records.has_key?("#{14}").inspect %>
                <% #@time_records.each do |time_record| %>
                <% (sdate.. Date.today).each do |date| %>

                  <% unless DateTime.parse("#{date}").strftime("%A") == "Saturday" || DateTime.parse("#{date}").strftime("%A") == "Sunday" %>
                    <tr>
                      <td>
                        <div class="input_field"> <%= date.strftime("%Y-%m-%d") %> </div>
                        <%= hidden_field_tag "time_record[current_month_timing][#{i}][date]", date.strftime("%Y-%m-%d") %>
                      </td>
                      <td><%= text_field_tag "time_record[current_month_timing][#{i}][in_time]", nil, :class => "input_field" %></td>
                      <td><%= text_field_tag "time_record[current_month_timing][#{i}][out_time]", nil, :class => "input_field" %></td>
                    </tr>
                    <% i += 1 %>
                  <% end %>

                <% end %>
              </table>
              <% i = 1 %>
              <div class="cleaner_h10"></div>
              <%= link_to "Cancel", user_root_path, class: "cancel_button float_r" %>
                <%= submit_tag "Save", class: "save_button float_r" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

app/views/time_records/create_multiple.html.erb
<%= render 'form' %>

app/views/time_records/edit_multiple.html.erb
<% require 'date' %>
<% require 'time_diff' %>

<div id="content_wrapper1">
  <div id="content1">
    <img class="scrollButtons left" src="" alt=""/>
    <div class="scroll" style="overflow: hidden;">
      <div class="scrollContainer" style="width: 4300px;">
        <div class="panel" id="home" style="float: left; position: relative;">
          <div id="contact_form">
            <% first_day = Time.now.strftime("%d").to_i %>
            <% user_fday = current_user.first_day_of_month %>
            <% #raise @time_records.inspect %>

            <%
            month = 1
            i = 1
            time_record = {}
          %>
            <% if user_fday <= Date.today.day
              month =  Date.today.month
            else
              month =  Date.today.month - 1
            end %>
            <% sdate =  Date.new(2013, month, user_fday) %>
            <% edate =  sdate + 30 %>

            <% t = @time_records.keys.last %>
            <%  #raise (@time_records[t]["date"].to_date).inspect %>
            <%= form_tag update_multiple_time_records_path, method: 'post' do |f| %>


              <table style="width: 100%; text-align: center" >
                <tr>
                  <th style="font-size: 20px;">Date</th>
                  <th style="font-size: 20px;">In Time</th>
                  <th style="font-size: 20px;">Out Time</th>
                </tr>

                <%  #raise @time_records.has_key?("#{14}").inspect %>
                <% #@time_records.each do |time_record| %>
                <% (sdate.. Date.today).each do |date| %>

                  <% unless DateTime.parse("#{date}").strftime("%A") == "Saturday" || DateTime.parse("#{date}").strftime("%A") == "Sunday" %>

                    <% if @time_records.has_key?("#{i}") %>
                      <% @time_records["#{i}"]["in_time"] = @time_records["#{i}"]["in_time"] %>
                      <% @time_records["#{i}"]["out_time"] = @time_records["#{i}"]["out_time"] %>
                    <% else %>
                      <% time_record = { "#{i}" => { "in_time" => "", "out_time" => "" } } %>
                      <% @time_records.merge!(time_record) %>
                    <% end %>
                    <tr>
                      <td>
                        <div class="input_field"> <%= date.strftime("%Y-%m-%d") %> </div>
                        <%= hidden_field_tag "time_record[current_month_timing][#{i}][date]", date.strftime("%Y-%m-%d") %>
                      </td>
                      <td><%= text_field_tag "time_record[current_month_timing][#{i}][in_time]", @time_records["#{i}"]["in_time"], :class => "input_field" %></td>
                      <td><%= text_field_tag "time_record[current_month_timing][#{i}][out_time]", @time_records["#{i}"]["out_time"], :class => "input_field" %></td>
                    </tr>
                    <% i += 1 %>
                  <% end %>
                <% end %>
              </table>
              <% i = 1 %>
              <div class="cleaner_h10"></div>
              <%= link_to "Cancel", user_root_path, class: "cancel_button float_r" %>
                <%= submit_tag "Save", class: "save_button float_r" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

app/views/time_records/edit_previous_month_timings.html.erb
<% require 'date' %>
<% require 'time_diff' %>

<div id="content_wrapper1">
  <div id="content1">
    <img class="scrollButtons left" src="" alt=""/>
    <div class="scroll" style="overflow: hidden;">
      <div class="scrollContainer" style="width: 4300px;">
        <div class="panel" id="home" style="float: left; position: relative;">
          <div id="contact_form">

            <% first_index = @previous_time_records.keys.first.to_s %>
            <% last_index = @previous_time_records.keys.last.to_s %>
            <% fd = @previous_time_records[first_index]["date"].to_date %>
            <% ld = @previous_time_records[first_index]["date"].to_date + 30 %>
            <% i = 1 %>
            <%  #raise (fd).inspect %>
            <%= form_tag update_previous_month_timings_time_records_path, method: 'post' do |f| %>

              <table style="width: 100%; text-align: center" >
                <tr>
                  <th style="font-size: 20px;">Date</th>
                  <th style="font-size: 20px;">In Time</th>
                  <th style="font-size: 20px;">Out Time</th>
                </tr>
                <% (fd..ld).each do |date| %>
                  <% unless DateTime.parse("#{date}").strftime("%A") == "Saturday" || DateTime.parse("#{date}").strftime("%A") == "Sunday" %>
                    <tr>
                      <td>
                        <div class="input_field"> <%= date.strftime("%Y-%m-%d") %> </div>
                        <%= hidden_field_tag "time_record[previous_month_timing][#{i}][date]", date.strftime("%Y-%m-%d") %>
                      </td>
                      <td><%= text_field_tag "time_record[previous_month_timing][#{i}][in_time]", @previous_time_records["#{i}"]["in_time"].blank? ? nil : @previous_time_records["#{i}"]["in_time"], :class => "input_field" %></td>
                      <td><%= text_field_tag "time_record[previous_month_timing][#{i}][out_time]", @previous_time_records["#{i}"]["out_time"].blank? ? nil : @previous_time_records["#{i}"]["out_time"], :class => "input_field" %></td>
                    </tr>
                    <% i += 1 %>
                  <% end %>
                <% end %>
              </table>
              <% i = 1 %>

              <div class="cleaner_h10"></div>
              <%= link_to "Cancel", time_records_path(previous: true), class: "cancel_button float_r" %>
                <%= submit_tag "Save", class: "save_button float_r" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

app/views/time_records/index.html.erb
<% require 'date' %>
<% require 'time_diff' %>

<div id="content_wrapper1">
  <div id="content1">
    <img class="scrollButtons left" src="" alt=""/>
    <div class="scroll" style="overflow: hidden;">
      <% unless @current_time_records.blank?%>
        <div class="link_button">
          <% if params[:previous] %>
            <%= link_to "Edit", edit_previous_month_timings_time_records_path %>
          <% else %>
            <%= link_to "Edit", edit_multiple_time_records_path %>
          <% end %>
        </div>
      <% end %>

      <div class="scrollContainer" style="width: 4300px;">
        <div class="panel" id="home" style="float: left; position: relative;">

          <% if @current_time_records.blank? %>
            <h2 style="text-align: center">No record found !</h2>
            <h3 style="text-align: center">Click <%= link_to 'here', new_time_record_path %> to create new timesheet</h3>
          <% else %>

            <% if params[:previous] %>
              <% f_index = @previous_time_records.keys.first.to_s %>
              <% f_month = @previous_time_records[f_index]["date"].to_date %>
              <% e_month = @previous_time_records[f_index]["date"].to_date + 30 %>
              <h1 style="text-align: left">Timings for the month of <%= f_month.strftime("%B")%> - <%=  e_month.strftime("%B") %></h1>
              <%= render "previous_month" %>
            <% else %>
              <% f_index = @current_time_records.keys.first.to_s %>
              <% f_month = @current_time_records[f_index]["date"].to_date %>
              <% e_month = @current_time_records[f_index]["date"].to_date + 30 %>
              <h1 style="text-align: left">Timings for the month of <%= f_month.strftime("%B")%> - <%=  e_month.strftime("%B") %></h1>
              <%= render "current_month" %>
            <% end %>

          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/time_records/new.erb
<%= render "form" %>