config/routes.rb
TimeRecording::Application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }

  root :to => 'home#index'

  resources :user
  
  resources :time_records do
    collection do
      post 'create_time_record'
      get 'edit_multiple'
      post 'update_multiple'
      post 'create_multiple'
      get 'edit_previous_month_timings'
      post 'update_previous_month_timings'
    end
  end

  resources :admins do
    member do
      get 'approve_user'
      get 'reject_user'
      delete 'destroy_user'
    end
  end

  match 'time_records' => 'time_records#index', as: :user_root
  match 'dashboard' => 'home#dashboard'#, as: :admin_index

  match 'about_us' => 'home#about_us'
  match 'instructions' => 'home#instructions'
  match 'contact' => 'home#contact'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeRecording</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application", "common" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="slider">
      <div id="header_wrapper">
        <div id="header">
          <a href="#home" style="text-decoration: none;">
            <h1>Time Manager</h1>
          </a>
        </div>
      </div>
      <div id="menu_wrapper">
        <div id="menu">
          <ul class="navigation">
            <% if user_signed_in? %>
              <li><%= link_to "Home", user_root_path %><span class="ui_icon home"></span></li>
            <% else %>
              <li><%= link_to "Home", root_path %><span class="ui_icon home"></span></li>
            <% end %>

            <li><%= link_to "About", about_us_path %><span class="ui_icon aboutus"></span></li>
            <li><%= link_to "Instructions", instructions_path %><span class="ui_icon services"></span></li>
            <li><%= link_to "Contact", contact_path %><span class="ui_icon contactus"></span></li>
            <% if user_signed_in? %>
              <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %><span class="ui_icon gallery"></span></li>
            <% else %>
              <li><%= link_to("Sign in", new_session_path(resource_name), :class => "", :onclick => "" ) %><span class="ui_icon gallery"></span></li>
            <% end %>
          </ul>
        </div>
      </div>
      <div>

      </div>
      <%= yield %>
      <div id="footer_wrapper">
        <div id="footer">
        	Copyright © 2013 Amit Sharma | Designed by Amit Sharma
        </div>
      </div>
    </div>
  </body>
</html>